import Head from "next/head";

export default function Category() {
  return (
    <section>
      <Head>
        <title>Category</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-dark">Category</p>
    </section>
  );
}
