import Head from "next/head";
import PageGrid from "./../components/Elements/PageGrid";
import NavBar from "../components/Navbar/Navbar";
import LongBanner from "../components/Cards/LongBanner";

export default function Home() {
  return (
    <PageGrid>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <LongBanner />
    </PageGrid>
  );
}
