import Head from "next/head";
import img from "./../public/assets/mainBanner.jpg";
import PageGrid from "./../components/Elements/PageGrid";
import NavBar from "../components/Navbar/Navbar";
import LongBanner from "../components/Cards/LongBanner";

export default function Home() {
  return (
    <PageGrid>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <LongBanner
        imgUrl={img}
        sloganTxt="BUY ME"
        msgTxt="Lorem Ipsum Lorem Ipsum"
        dscTxt="product description"
        buttonMargin="mt-2"
        buttonTxt="Shop"
        styleWrapper="absolute bottom-14 left-8"
        stylingSlogan="text-2xl mb-2 font-bold tracking-wider"
      />
    </PageGrid>
  );
}
